stage_list:
    - {set: Processing, name: TrackMLFeatureStore, config: prepare_quickstart.yaml, batch_config: configs/batch_cpu_default.yaml}
    #- {set: Processing, name: TrackMLFeatureStore, config: prepare_alldata.yaml, batch_config: configs/batch_cpu_default.yaml}
    #- {set: Embedding, name: LayerlessEmbedding, config: train_quickstart_embedding.yaml, batch_config: configs/batch_gpu_default.yaml, resume_id: }
    #- {set: Filter, name: PyramidFilter, config: train_quickstart_filter.yaml, batch_config: configs/batch_gpu_default.yaml, batch_setup: True}
    #- {set: GNN, name: InteractionGNN, config: train_quickstart_GNN.yaml, batch_config: configs/batch_gpu_default.yaml, resume_id: }