# Location of libraries
libraries:
    model_library: LightningModules
    #artifact_library: /global/cfs/cdirs/m3443/data/lightning_models/lightning_checkpoints
    artifact_library: '/global/cscratch1/sd/aalap/Tracking-ML-Exa.TrkX/exatrkx/data/lightning_models/lightning_checkpoints'
    

# The lines you would like/need in a batch script before the call to pipeline.py
custom_batch_setup:
    #- conda activate exatrkx-test
    - conda activate exatrkx-hsf
    
# If you need to set up some environment before a batch is submitted, define it here in order of commands to run
command_line_setup:
    #- module load cgpu
    - module load nvidia
    #- module load cudatoolkit/11.4
    - module load python
    
# If you need to run jobs serially, set to true
serial: False

# Which logger to use - options are Weights & Biases [wandb], TensorBoard [tb], Common Metadata Framework [cmf] or [None]
#logger: tb
logger: cmf 